### ISSUE TITLE
Annotation background border 

### ISSUE THREAD

**Issue by chochart** [biobakery/graphlan#6]
Hi,

I would like to know if is there any way to display a unique color for taxon border usually visible when the transparency is set on the annotation background. I tried several options, but in vain. 
![lefse-graphlan-bw](https://user-images.githubusercontent.com/18531562/109639159-26e35e80-7b4f-11eb-8e28-9141ad67acd7.png)
![lefse-graphlan-bw-nobg](https://user-images.githubusercontent.com/18531562/109639171-2a76e580-7b4f-11eb-9bfb-10a767dab65d.png)

Thank you
Corentin

**Comment by fasnicar** [comment]
Hello @chochart, unfortunately, setting the edge color of the background annotation is not implemented in GraPhlAn yet. Would changing the color of your background annotations from grey to something else work for you instead?

Thanks,
Francesco

**Comment by chochart** [comment]
Already done in color. I was trying to figure it out if the plot still clear with a grey or white/black theme. The price for a colored figure can get expensive in some journals. 

Thanks,
Corentin
